In [1]:
import tensorflow as tf

initializing the input sensor

In [2]:
a = tf.constant([7,8,13,11],dtype = tf.float64)
b = tf.constant([2,13,14,5],dtype = tf.float64)

printing the input sensor

In [3]:
print('a',a)
print('b',b)

a tf.Tensor([ 7.  8. 13. 11.], shape=(4,), dtype=float64)
b tf.Tensor([ 2. 13. 14.  5.], shape=(4,), dtype=float64)


finding truth value

In [4]:
res = tf.math.less(x=a,y=b)

printing results

In [5]:
print('Result:',res)

Result: tf.Tensor([False  True  True False], shape=(4,), dtype=bool)
